Quiz3/Quiz3/Quiz3/Models/DBHandler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace Quiz3.Models
{
    public class DBHandler
    {
        private SqlConnection con;
        private void connection()
        {
            string constring = ConfigurationManager.ConnectionStrings["Test2"].ToString();
            con = new SqlConnection(constring);
        }

        public bool InsertItem(User iList)
        {
            connection();
            string query = "INSERT INTO User VALUES('" + iList.Name + "','" + iList.SalesAgent + "','" + iList.VehicleName + "','" + iList.OSP + "','" + iList.DSP + ")";
            SqlCommand cmd = new SqlCommand(query, con);
            con.Open();
            int i = cmd.ExecuteNonQuery();
            con.Close();

            if (i >= 1)
                return true;
            else
                return false;
        }

        public List<User> GetList()
        {
            connection();
            List<User> ilist = new List<User>();
            string query = "SELECT * FROM User";
            SqlCommand cmd = new SqlCommand(query, con);
            SqlDataAdapter adapter = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();

            con.Open();
            adapter.Fill(dt);
            con.Close();

            foreach(DataRow dr in dt.Rows)
            {
                ilist.Add(new User
                {
                    ID = Convert.ToInt32(dr["ID"]),
                    Name = Convert.ToString(dr["Name"]),
                    SalesAgent = Convert.ToString(dr["Agent"]),
                    VehicleName = Convert.ToString(dr["Item"]),
                    OSP = Convert.ToDouble(dr["SRP"]),
                    DSP = Convert.ToDouble(dr["TSP"])

                });
            }

            return ilist;
        }
    }
}

Quiz3/Quiz3/Quiz3/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Quiz3.Models
{
    public class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SalesAgent { get; set; }
        public string VehicleName { get; set; }
        public double OSP { get; set; }
        public double DSP { get; set; }
        public double SalesDiscount { get { return ((OSP - DSP) / OSP) * 100 ; }  }

        public string Condition
        {
            get
            {
                if (DSP > SalesDiscount)
                {
                    return "INVALID";
                }
                else
                {
                    return "SUCCESS";
                }
            }
        }
        public double test = 100;
        //add sales agent
    }
}

Quiz3/Quiz3/Quiz3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiz3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Quiz3/Quiz3/Quiz3/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiz3.Models;
using Quiz3.App_Code;
using System.Data.SqlClient;

namespace Quiz3.Controllers
{
    public class QuizController : Controller
    {
        // GET: Quiz
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            User principal = new User();
            return View(principal);
        }

        [HttpPost]

        public ActionResult Add(User user)
        {
            using (SqlConnection con = new SqlConnection(Helper.GetCon()))
            {
                con.Open();
                string query = @"INSERT INTO Yikes VALUES(@Name, @Agent, @Item, @SRP, @TSP, @SalesDiscount)";
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@Name", user.Name);
                    cmd.Parameters.AddWithValue("@Agent", user.SalesAgent);
                    cmd.Parameters.AddWithValue("@Item", user.VehicleName);
                    cmd.Parameters.AddWithValue("@SRP", user.OSP);
                    cmd.Parameters.AddWithValue("@TSP", user.DSP);
                    cmd.Parameters.AddWithValue("@SalesDiscount", user.SalesDiscount);
                    cmd.ExecuteNonQuery();
                }
            }

            Session["Name"] = user.Name;
            Session["Agent"] = user.SalesAgent;
            Session["Item"] = user.VehicleName;
            Session["SRP"] = user.OSP;
            Session["TSP"] = user.DSP;
            Session["Discount"] = user.SalesDiscount;
            Session["Condition"] = user.Condition;

            return RedirectToAction("Index");
        }


    }
}

Quiz3/Quiz3/Quiz3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Quiz3/Quiz3/Quiz3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Quiz3/Quiz3/Quiz3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Quiz3/Quiz3/Quiz3/Views/Quiz/Add.cshtml
@model Quiz3.Models.User

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalesAgent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalesAgent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalesAgent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Quiz3/Quiz3/Quiz3/Views/Quiz/Index.cshtml
@{
    Layout = null;
}

@using Quiz3.Models;

<!DOCTYPE html>

<html>
<head>
    <metaname ="viewport" content="width=device-width" />
    <title>Index</title>
</head>

<body>
    <table border="1" cellpadding="2" cellspacing="2">
        <tr>
            <td>Name:</td>
            <td>@Session["Name"]</td>
        </tr>
        <tr>
            <td>Sales Agent</td>
            <td>@Session["Agent"]</td>
        </tr>
        <tr>
            <td>Item Name</td>
            <td>@Session["Item"]</td>
        </tr>
        <tr>
            <td>Sales Retail Price</td>
            <td>@Session["SRP"]</td>
        </tr>
        <tr>
            <td>Target Sales Price</td>
            <td>@Session["TSP"]</td>
        </tr>
        <tr>
            <td>Discount</td>
            <td>@Session["SalesDiscount"]</td>
        </tr>
        <tr>
            <td>Is the discount valid?</td>
            <td>@Session["Condition"]</td>
        </tr>
    </table>

    <input type="button" value="Input Session" onclick="location.href='@Url.Action("Add", "Quiz")'" />
</body>
</html>

Quiz3/Quiz3/Quiz3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>